[build]
  publish = "."

# まず config.yml は素直に返す
[[redirects]]
  from = "/admin/config.yml"
  to   = "/admin/config.yml"
  status = 200
  force = true

# それ以外の /admin/* は index.html にフォールバック
[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200
