backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: ""
    create: false
    fields:
      - { label: "ファイル名", name: "path", widget: "hidden" }
      - { label: "本文",     name: "body", widget: "markdown" }
