backend:
  name: git-gateway
  branch: main  # または "master" に合わせてください

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "ページ"
    files:
      - file: "index.html"
        label: "トップページ"
        name: "index"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "text" }